# Site wide configuration

title:  "Be brave. Take risks." - Paulo Coelho
locale: en_US
description: Adventure, learning, tech startups, code, travel, and poker. Standard NYC blog.
logo: site-logo.png
search: true
url: 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Steph Reaves
  avatar: bio-photo.jpg
  email: Stephanie.Reaves@gmail.com
  disqus-shortname:
  twitter: StephReaves
  facebook: sreaves2
  github: StephReaves
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: StephReaves
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify: